---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    platform: amd64
    #image: geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest
    image: ghcr.io/grokon/molecule-containers:${MOLECULE_DISTRO:-debian-bullseye}
    override_command: false
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
verifier:
  name: ansible
