---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    #image: geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest
    image: ghcr.io/grokon/molecule-containers:${MOLECULE_DISTRO:-debian-bullseye}
    override_command: false
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
    ANSIBLE_REMOTE_TMP: /tmp/.ansible-${MOLECULE_DISTRO:-debian-bullseye}
verifier:
  name: ansible
