---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify Docker is installed
      ansible.builtin.command:
        cmd: docker --version
      register: docker_version
      changed_when: false
      failed_when: "'Docker version' not in docker_version.stdout"
