---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    branches:
      - master
      - main
      - testing
    paths-ignore:
      - "**/README.md"
      - "**/CHANGELOG.md"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true


jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian-bullseye

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python3 -m pip install ansible molecule[docker] docker
      - name: Test with molecule
        run: |
          molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout
#         uses: actions/checkout@v3
#         with:
#           path: "${{ github.repository }}"
#       - name: molecule
#         uses: buluma/molecule-action@v5.0.1
#         with:
#           command: lint
#   test:
#     needs:
#       - lint
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         scenario:
#           - image: "ghcr.io/grokon/molecule-containers"
#             tag: "debian-bullseye"

#     steps:
#       - name: checkout
#         uses: actions/checkout@v3
#         with:
#           path: "${{ github.repository }}"
#       - name: molecule
#         uses: buluma/molecule-action@v5.0.1
#         with:
#           image: ${{ matrix.scenario.image }}
#           options: parallel
#           tag: ${{ matrix.scenario.tag }}
